function fig = CAMEG()
% ___________________________________________________________________________
% Connectivity analysis of MEG data (CA-MEG)
%
% Copyright 2016 Cincinnati Children's Hospital Medical Center
% Reference
%
%
% v1.0 Vahab Youssofzadeh 21/07/2016
% Email: Vahab.Youssofzadeh@cchmc.org
%
% If you use this code for a publication, please ask Vahab YoussofZadeh
%  for the correct reference to cite.
% ___________________________________________________________________________
clc, close all

p = mfilename('fullpath');
cd(fileparts(p));
display('your current working path is,')
cd

r = 100;
col = [0.4020 0.7072 0.1014];
f = figure(...
    'Color',[1 1 1], ...
    'PaperPosition',[18 180 576 432], ...
    'PaperUnits','points', ...
    'Position',[850 650 390 280], ...
    'Tag','Main', ...
    'NumberTitle','off', ...
    'DoubleBuffer','on', ...
    'Visible','on', ...
    'MenuBar','none', ...
    'Color',[0.4 0.4 0.9],...
    'NumberTitle','off',...
    'Name','CA-MEG v.1', ...
    'ToolBar','none');

h = uicontrol('Parent',f, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'FontSize',11, ...
    'ListboxTop',0, ...
    'Position',[16 r 280 36], ...
    'String',['                      CA-MEG                           ';
    '      (Connectivity analysis of MEG data)              '], ...
    'Style','text', 'backgroundcolor',[0.4 0.4 0.9],...
    'ForegroundColor','w',...
    'Tag','StaticText5');

f1 = uimenu('Label','Data prepration');
f11 = uimenu(f1,'Label','MRI', ...
    'Callback','cameg_datapre_readmri');
f12 = uimenu(f1,'Label','Surface', ...
    'Callback','cameg_datapre_readsurf');
f13 = uimenu(f1,'Label','Mesh', ...
    'Callback','cameg_datapre_readmesh');
f14 = uimenu(f1,'Label','Cort thickness (optional)', ...
    'Callback','cadsum_datapre_CT');
f15 = uimenu(f1,'Label','MEG sources');
uimenu(f15,'Label','Single-subject/multi-trial data', ...
    'Callback','cameg_datapre_readdata_mt');
uimenu(f15,'Label','Averaged sources/single-trial data', ...
    'Callback','cameg_datapre_readdata_ave');
% uimenu(f15,'Label','Multi-subject (group) data', ...
%     'Callback','cameg_datapre_readdata_gs');
uimenu(f15,'Label','Multi-condition/multi-trial data', ...
    'Callback','cameg_datapre_readdata_mc');
f16 = uimenu(f1,'Label','ROI sel update (optioanl)',...
    'Callback','cameg_datapre_roiupdate');

f2 = uimenu('Label','Process');
f21 = uimenu(f2,'Label','Compute conn');
uimenu(f21,'Label','PSI (phase slope index)', ...
    'Callback','cameg_conn_psi');
f22 = uimenu(f2,'Label','Freq of interest',...
    'Callback','cameg_freqSel');


f3 = uimenu('Label','Visualisation');
f31 = uimenu(f3,'Label','Connectogtam (circularGraph)',...
    'Callback','cameg_VisCirc');
f32 = uimenu(f3,'Label','Surface Vis (BrainNet)',...
    'Callback','cameg_VisSurf');
f33 = uimenu(f3,'Label','Con Mat', ...
    'Callback','cameg_VisConMat');
f34 = uimenu(f3,'Label','Data (sources)', ...
    'Callback','cameg_VisData');
f35 = uimenu(f3,'Label','Conn (flux)', ...
    'Callback','cameg_VisFlux');
f36 = uimenu(f3,'Label','PSD (sources)', ...
    'Callback','cameg_VisPSD');

f4 = uimenu('Label','About');
f41 = uimenu(f4,'Label','Credit',...
    'Callback','cameg_ceredit');

h5 = uicontrol('Parent',f, ...
    'Units','points', ...
    'BackgroundColor',col, ...
    'Position',[72 r-15 166 16], ...
    'String','Close', ...
    'CallBack', 'cameg_closeall');

if nargout > 0, fig = f0; end