function fig = cameg_datapre()
% ___________________________________________________________________________
% CADSuM (Classification of AD Sufferers using Machine Learning)
%
% Copyright 2016 Cincinnati Children's Hospital Medical Center
% Reference 
% 
% 
% v1.0 Vahab Youssofzadeh 21/07/2016
% email: Vahab.Youssofzadeh@cchmc.org
% ___________________________________________________________________________
disp('cameg data prepration ...')
col = [0.8020 0.9072 0.4014];

global f1

f1 = figure(...
'Color',[1 1 1], ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[450 250 390 210], ...
	'Tag','Main', ...
    'NumberTitle','off', ...
    'DoubleBuffer','on', ...
    'Visible','on', ...	
    'NumberTitle','off',...
    'MenuBar','none', ...
	'Name','ToolBox : CA-MEG v.1', ...
    'ToolBar','none');
h1 = uicontrol('Parent',f1, ...
	'Units','points', ...
	'BackgroundColor',col, ...
	'Position',[72 95 166 16], ...
	'String','Import MEG sources', ...
	'CallBack','cameg_datapre_readdata');
h2 = uicontrol('Parent',f1, ...
	'Units','points', ...
	'BackgroundColor',col, ...
	'Position',[72 75 166 16], ...
	'String','Import MRI', ...
	'CallBack','cameg_datapre_readmri');
h3 = uicontrol('Parent',f1, ...
	'Units','points', ...
	'BackgroundColor',col, ...
	'Position',[72 55 166 16], ...
	'String','Import surface', ...
	'CallBack','cameg_datapre_readsurf');
h4 = uicontrol('Parent',f1, ...
	'Units','points', ...
	'BackgroundColor',col, ...
	'Position',[72 35 166 16], ...
	'String','Import mesh', ...
	'CallBack','cameg_datapre_readmesh');
h5 = uicontrol('Parent',f1, ...
	'Units','points', ...
	'BackgroundColor',col, ...
	'Position',[72 15 166 16], ...
	'String','Import cort thickness (optional)', ...
	'CallBack','cadsum_datapre_CT');
h6 = uicontrol('Parent',f1, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',11, ...
	'ListboxTop',0, ...
	'Position',[16 110 280 36], ...
	'String','Data from Brainstorm OR Freesurfer', ...
	'Style','text', ...
	'Tag','StaticText5');
% h7 = uicontrol('Parent',f1, ...
% 	'Units','points', ...
% 	'BackgroundColor',col, ...
% 	'Position',[1 60 66 16], ...
% 	'String','Check Reg', ...
% 	'CallBack','cadsum_preprocess_checkReg');
if nargout > 0, fig = f1; end
